#pragma once

#define MASTER_LEFT

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE

#define NO_MUSIC_MODE
#define LAYER_STATE_16BIT

#define TAPPING_TERM 240
#define TAPPING_TERM_PER_KEY

#define DISABLE_LEADER

#define MOUSEKEY_TIME_TO_MAX 60

#define COMBO_ONLY_FROM_LAYER 0
#define COMBO_SHOULD_TRIGGER 1
#define COMBO_TERM 30

#define ADAPTIVE_ONLY_FROM_LAYER 0
#define ADAPTIVE_TERM 140
