#pragma once

#define MASTER_LEFT

#define TAPPING_TERM 240
#define IGNORE_MOD_TAP_INTERRUPT
#define PERMISSIVE_HOLD

#define MOUSEKEY_TIME_TO_MAX 60

#define COMBO_ONLY_FROM_LAYER 0
#define COMBO_SHOULD_TRIGGER 1
#define COMBO_TERM 35

#define BOTH_SHIFTS_TURNS_OS_CAPS_WORD

#define ADAPTIVE_ONLY_FROM_LAYER 0
#define ADAPTIVE_TERM 140
